<script setup>
import { ref, watch, computed } from 'vue';
import { marked } from 'marked';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { usePage, router } from '@inertiajs/vue3';
import ConfirmationModal from '@/Components/UI/ConfirmationModal.vue';

const props = defineProps({
    report: Object,
    class: String
});

const emit = defineEmits(['reset']);

const page = usePage();
const userName = page.props.auth.user.name; 
const companyName = "iTech Media Logic"; 

const rawMarkdown = ref('');
const isExporting = ref(false);
const showArchiveModal = ref(false);

watch(() => props.report, (newVal) => {
    if (newVal) {
        rawMarkdown.value = newVal.report;
    }
}, { immediate: true });

// Processed content for the PREVIEW (Dark Theme)
const previewContent = computed(() => {
    return marked.parse(rawMarkdown.value);
});

// Processed content for the PDF (Clean, Professional, Stripped Header)
const pdfContent = computed(() => {
    // Remove the AI's generated header lines to avoid duplication with our dynamic header
    let cleanMd = rawMarkdown.value;
    
    // Remove specific header lines often generated by AI
    cleanMd = cleanMd.replace(/^(#\s*)?Weekly Progress Report.*/im, '');
    cleanMd = cleanMd.replace(/^Date Range:.*$/im, '');
    cleanMd = cleanMd.replace(/^Intern:.*$/im, '');
    cleanMd = cleanMd.replace(/^Position:.*$/im, '');
    cleanMd = cleanMd.replace(/^Company:.*$/im, '');
    
    return marked.parse(cleanMd.trim());
});

const archiveToVault = () => {
    showArchiveModal.value = true;
};

const confirmArchive = () => {
    const reportId = props.report.id || props.report._id;
    
    if (reportId) {
        router.delete(route('reports.destroy', reportId), {
            onSuccess: () => {
                showArchiveModal.value = false;
                emit('reset');
            },
            onError: (errors) => {
                console.error('Archive failed:', errors);
            }
        });
    } else {
        console.error('Report ID missing:', props.report);
    }
};

const exportToPDF = async () => {
    isExporting.value = true;
    const element = document.getElementById('report-document');
    
    // Show element in DOM
    element.style.display = 'block';
    
    try {
        // Capture the entire element
        // We use a white background and ensure high scale
        const canvas = await html2canvas(element, {
            scale: 2, 
            useCORS: true,
            allowTaint: true,
            backgroundColor: '#FFFFFF',
            // Ensure we capture the full scroll height
            width: element.offsetWidth, 
            height: element.scrollHeight,
            windowWidth: element.offsetWidth, 
            windowHeight: element.scrollHeight
        });
        
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = 210;
        const pdfHeight = 297;
        const margin = 25; // 25mm margin all around
        const contentWidth = pdfWidth - (margin * 2); // 160mm
        // Reduce content height slightly more to ensure safe distance from footer (e.g. 15mm extra buffer)
        // A4 Height (297) - Top (25) - Bottom (25) - Buffer (15) = 232mm effective content height
        const contentHeight = pdfHeight - (margin * 2) - 15; 
        
        // Calculate canvas dimensions mapping
        const canvasWidth = canvas.width;
        const canvasHeight = canvas.height;
        const scaleFactor = contentWidth / canvasWidth; // Scale to fit width
        
        // Height of one PDF page content in canvas pixels
        const pageHeightInCanvasPx = contentHeight / scaleFactor;
        
        let currentSourceY = 0;
        let pageNum = 1;
        
        // We need to pre-calculate total pages for the footer "Page X of Y"
        // This is an estimate; actual loop might vary slightly but usually accurate for linear content
        const totalPages = Math.ceil(canvasHeight / pageHeightInCanvasPx);

        while (currentSourceY < canvasHeight) {
            if (pageNum > 1) {
                pdf.addPage();
            }

            // Determine slice height for this page
            const remainingCanvasHeight = canvasHeight - currentSourceY;
            const sliceHeightPx = Math.min(remainingCanvasHeight, pageHeightInCanvasPx);
            
            // Create a temporary canvas for this slice
            const tempCanvas = document.createElement('canvas');
            tempCanvas.width = canvasWidth;
            tempCanvas.height = sliceHeightPx;
            const ctx = tempCanvas.getContext('2d');
            
            // Draw the slice from the original canvas
            ctx.fillStyle = '#FFFFFF';
            ctx.fillRect(0, 0, tempCanvas.width, tempCanvas.height);
            ctx.drawImage(
                canvas, 
                0, currentSourceY, canvasWidth, sliceHeightPx, // Source rect
                0, 0, canvasWidth, sliceHeightPx // Dest rect
            );
            
            const sliceImgData = tempCanvas.toDataURL('image/png');
            
            // Calculate height on PDF
            const sliceHeightPdf = sliceHeightPx * scaleFactor;
            
            // Add the slice content (offset by top margin)
            pdf.addImage(sliceImgData, 'PNG', margin, margin, contentWidth, sliceHeightPdf);
            
            // --- HEADER ---
            pdf.setTextColor(0, 0, 0);
            pdf.setFontSize(14);
            pdf.setFont('helvetica', 'bold');
            pdf.text('WEEKLY PROGRESS REPORT', margin, 15);
            
            pdf.setFontSize(10);
            pdf.setFont('helvetica', 'normal');
            pdf.setTextColor(100);
            pdf.text(companyName, margin, 20);
            
            pdf.setFontSize(8);
            const periodText = (props.report.period?.start || 'N/A') + ' - ' + (props.report.period?.end || 'N/A');
            pdf.text(periodText, pdfWidth - margin, 15, { align: 'right' });
            pdf.text('Internship Program', pdfWidth - margin, 20, { align: 'right' });
            
            // Header Line
            pdf.setDrawColor(200);
            pdf.setLineWidth(0.5);
            pdf.line(margin, 22, pdfWidth - margin, 22);

            // --- FOOTER ---
            // Footer Line
            pdf.line(margin, pdfHeight - 20, pdfWidth - margin, pdfHeight - 20);
            
            pdf.setFontSize(8);
            pdf.setTextColor(150);
            pdf.text('Generated via Internal Journal System', margin, pdfHeight - 15);
            pdf.text(`Page ${pageNum} of ${totalPages}`, pdfWidth - margin, pdfHeight - 15, { align: 'right' });
            
            // Prepare for next loop
            currentSourceY += sliceHeightPx;
            pageNum++;
        }

        const fileName = props.report.period?.start ? props.report.period.start.replace(/ /g, '-') : 'Report';
        pdf.save(`Weekly-Report-${fileName}.pdf`);
    } catch (error) {
        console.error('PDF Export failed:', error);
    } finally {
        element.style.display = 'none';
        isExporting.value = false;
    }
};

const exportToDocs = () => {
    // Basic doc export
    const content = props.report.report;
    const docContent = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head><title>Weekly Report</title></head>
        <body style="font-family: Arial, sans-serif;">
            <div style="border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 20px;">
                <h1 style="text-transform: uppercase; margin: 0;">Weekly Progress Report</h1>
                <p style="margin: 5px 0 0 0; color: #666; font-weight: bold;">${companyName}</p>
                <p><strong>Intern:</strong> ${userName}</p>
                <p><strong>Period:</strong> ${props.report.period?.start || 'N/A'} - ${props.report.period?.end || 'N/A'}</p>
            </div>
            ${marked.parse(content)}
        </body>
        </html>
    `;
    
    const blob = new Blob(['\ufeff', docContent], {
        type: 'application/msword'
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const docFileName = props.report.period?.start ? props.report.period.start.replace(/ /g, '-') : 'Report';
    link.download = `Weekly-Report-${docFileName}.doc`;
    link.click();
    URL.revokeObjectURL(url);
};
</script>

<template>
    <div :class="['relative flex flex-col h-full overflow-hidden group/preview', props.class]">
        <!-- Main Container -->
        <div class="absolute inset-0 bg-[#1A1A1A] rounded-3xl border border-white/[0.05] shadow-2xl"></div>
        
        <div class="relative h-full flex flex-col p-6 md:p-10">
            <!-- Header -->
            <div class="flex flex-col gap-6 mb-8 shrink-0">
                <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                    <div>
                        <p class="text-[10px] uppercase tracking-[0.2em] text-[#A68B6A] font-bold">Generated Documentation</p>
                        <h2 class="text-2xl md:text-3xl font-bold text-[#E3D5C1] font-cinzel">Weekly Progress Report</h2>
                        <p class="text-[#A68B6A]/60 text-[10px] uppercase tracking-widest mt-1 font-bold">
                            {{ report.period?.start || 'N/A' }} — {{ report.period?.end || 'N/A' }}
                        </p>
                    </div>
                </div>

                <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 w-full">
                    <button 
                        @click="archiveToVault"
                        class="h-12 bg-white/[0.04] hover:bg-white/[0.08] text-[#8C6A4A] rounded-xl border border-[#8C6A4A]/20 hover:border-[#8C6A4A]/40 transition-all flex items-center justify-center gap-2 text-[10px] uppercase tracking-widest font-bold"
                    >
                        <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" /></svg>
                        <span>To Vault</span>
                    </button>
                    <button 
                        @click="exportToDocs"
                        class="h-12 bg-white/[0.04] hover:bg-white/[0.1] text-[#E3D5C1] rounded-xl border border-white/[0.08] transition-all flex items-center justify-center gap-2 text-[10px] uppercase tracking-widest font-bold"
                    >
                        <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                        <span>Export DOCS</span>
                    </button>
                    <button 
                        @click="exportToPDF"
                        :disabled="isExporting"
                        class="h-12 sm:col-span-2 lg:col-span-1 bg-[#A68B6A] hover:bg-[#C9B79C] text-[#1B1B1B] rounded-xl transition-all shadow-xl flex items-center justify-center gap-2 text-[10px] uppercase tracking-widest font-black disabled:opacity-50"
                    >
                        <svg v-if="!isExporting" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" /></svg>
                        <svg v-else class="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                        <span>{{ isExporting ? 'Preparing...' : 'Export PDF' }}</span>
                    </button>
                </div>
            </div>

            <!-- Scrollable Content -->
            <div class="flex-1 overflow-y-auto pr-2 scrollbar-style px-1">
                <!-- Hidden Actual Export View (White Professional PDF) -->
                <div id="report-document" class="hidden-for-export">
                    <div style="width: 794px; background-color: #ffffff; color: #000000; font-family: 'Arial', sans-serif; padding: 0px; box-sizing: border-box; overflow: hidden; position: relative;">
                        <div style="padding: 40px; min-height: 1000px;">
                            <div class="pdf-content prose prose-sm max-w-none 
                                prose-headings:text-black prose-headings:font-bold prose-headings:uppercase prose-headings:tracking-wide
                                prose-p:text-gray-900 prose-p:leading-relaxed
                                prose-li:text-gray-900 prose-li:marker:text-black
                                prose-strong:text-black prose-strong:font-bold" 
                                v-html="pdfContent">
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Live Preview View (Original Dark Theme) -->
                <div class="prose prose-invert max-w-none 
                    prose-h1:text-2xl prose-h1:font-bold prose-h1:text-[#E3D5C1] prose-h1:border-b prose-h1:border-white/10 prose-h1:pb-4 prose-h1:mb-6
                    prose-h2:text-xl prose-h2:text-[#A68B6A] prose-h2:mt-8 prose-h2:mb-3
                    prose-h3:text-lg prose-h3:text-[#E3D5C1]
                    prose-p:text-[#E3D5C1]/80 prose-p:leading-relaxed
                    prose-ul:my-4 prose-li:marker:text-[#A68B6A] prose-li:text-[#E3D5C1]/70
                    prose-strong:text-[#E3D5C1] prose-strong:font-bold
                    pb-10
                " v-html="previewContent"></div>
            </div>
        </div>
    </div>

    <!-- Archive Confirmation Modal -->
    <ConfirmationModal 
        :show="showArchiveModal"
        title="Consign to the Vault?"
        message="This report shall be cast into the Sunken Vault, where forgotten chronicles rest. You may summon it back from the depths should the need arise."
        confirm-text="Cast into Vault"
        cancel-text="Keep in Archives"
        type="warning"
        @close="showArchiveModal = false"
        @confirm="confirmArchive"
    />
</template>

<style scoped>
.scrollbar-style::-webkit-scrollbar {
    width: 6px;
}
.scrollbar-style::-webkit-scrollbar-track {
    background: rgba(255, 255, 255, 0.02);
}
.scrollbar-style::-webkit-scrollbar-thumb {
    background: rgba(166, 139, 106, 0.3);
    border-radius: 3px;
}
.scrollbar-style::-webkit-scrollbar-thumb:hover {
    background: rgba(166, 139, 106, 0.5);
}

/* Ensure the export container is hidden from view but renderable */
.hidden-for-export {
    display: none; /* Toggled by script */
    position: absolute;
    top: -9999px;
    left: -9999px;
}

/* Force PDF typography to be black/clean */
.pdf-content :deep(h1), .pdf-content :deep(h2), .pdf-content :deep(h3) {
    color: #000 !important;
    margin-top: 1.5em;
    margin-bottom: 0.5em;
}
.pdf-content :deep(p), .pdf-content :deep(li) {
    color: #111 !important;
}
.pdf-content :deep(strong) {
    color: #000 !important;
}

/* Typography Overrides for HTML content inside PREVIEW (Dark) */
:deep(.prose h1) { font-family: 'Cinzel', serif; letter-spacing: 0.05em; }
:deep(.prose h2) { font-family: 'Cinzel', serif; letter-spacing: 0.025em; border-left: 2px solid #A68B6A; padding-left: 1rem; }
:deep(.prose strong) { color: #A68B6A; }
</style>
